### ISSUE TITLE
这么棒的博客，非常期待一个安装部署教程，谢谢。

### ISSUE THREAD

**Issue by shenweiyan** [ShixiangWang/home#1]
如题！

**Comment by ShixiangWang** [comment]
这个是基于 [hugo-ivy](https://github.com/yihui/hugo-ivy) 的修改版本。只要懂点 [Hugo](https://gohugo.io/) 就可以了，如果是 R 用户可以配合 Blogdown 包使用。

如果你想要使用，下载 <https://github.com/ShixiangWang/home/releases/tag/v1.0>，这是我之前刚弄好没加什么内容的时候备份的。只要修改一些个人信息就可以使用了。

本地预览命令应该是 `hugo server`。

目前没有打算写一个详细的教程，不好意思。如果你有精力，折腾的时候可以全面记录一下。我很欢迎在 README 中添加相关说明。

祝好，
诗翔

**Comment by ShixiangWang** [comment]
看到你 Fork 了该仓库，这个操作我不是很建议，因为已经添加了不少内容，你修改起来会很麻烦。

下载  <https://github.com/ShixiangWang/home/releases/tag/v1.0>，删除 .git 目录，然后你自己创建一个git仓库进行版本控制是一个更好的选择。
